name = "cloudflare-worker-loki"
type = "webpack"
main = "src/index.js"
account_id = "619be86ad540dd03a3448fb25a99f515"
workers_dev = true
usage_model = "unbound"
route = ""
zone_id = "a3fa3c23b84c439073d6d40f8d9b8369"

[vars]
lokiHost = "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
